Hola!
[Title1]
Meter=String
MeterStyle=TitleStyle
Text=Rihanna calls out Snapchat for tone-deaf ad that made light of domestic violence #Separator#
LeftMouseUpAction=http://feedproxy.google.com/~r/Techcrunch/~3/Q3NVXnhfyLQ/
[Title2]
Meter=String
MeterStyle=TitleStyle
Text=Florida university bridge collapses 'leaving people trapped' #Separator#
LeftMouseUpAction=http://www.bbc.co.uk/news/world-us-canada-43418898
[Title3]
Meter=String
MeterStyle=TitleStyle
Text=If you go into space for a long time, you come back a genetically different person #Separator#
LeftMouseUpAction=https://qz.com/1230081/nasa-astronaut-scott-kellys-dna-appears-to-have-remained-permanently-changed-after-his-year-on-the-international-space-station/
[Title4]
Meter=String
MeterStyle=TitleStyle
Text=950-Ton Pedestrian Bridge Collapses at Florida International University #Separator#
LeftMouseUpAction=http://feedproxy.google.com/~r/time/topstories/~3/H2rqlBGs-KQ/
[Title5]
Meter=String
MeterStyle=TitleStyle
Text=New Surveillance Video Shows School Resource Officer Outside During Parkland Shooting #Separator#
LeftMouseUpAction=http://feedproxy.google.com/~r/time/topstories/~3/eEX84ZR4j-M/
[Title6]
Meter=String
MeterStyle=TitleStyle
Text=US punishes 19 Russians over vote meddling and cyber-attacks #Separator#
LeftMouseUpAction=http://www.bbc.co.uk/news/world-us-canada-43419809
[Title7]
Meter=String
MeterStyle=TitleStyle
Text=The Vatican doctored a photo that showed Pope Benedict didn’t read books on Francis #Separator#
LeftMouseUpAction=https://qz.com/1230096/vatican-photo-official-release-of-doctored-image-is-criticized-by-the-ap/
[Title8]
Meter=String
MeterStyle=TitleStyle
Text=‘Shame on You.’ Rihanna Calls Out Snapchat for Ad Making Light of Domestic Violence #Separator#
LeftMouseUpAction=http://feedproxy.google.com/~r/time/topstories/~3/w2qoeTOnukU/
[Title9]
Meter=String
MeterStyle=TitleStyle
Text=Mariam Moustafa: Egyptian teen's Nottingham death sparks anger #Separator#
LeftMouseUpAction=http://www.bbc.co.uk/news/uk-england-nottinghamshire-43413487
[Title10]
Meter=String
MeterStyle=TitleStyle
Text=Several beauty products contain baby foreskin cells, urine, or snail extract #Separator#
LeftMouseUpAction=https://quartzy.qz.com/1230002/sandra-bullock-and-cate-blanchett-had-a-penis-facial-its-not-that-strange/
[Title11]
Meter=String
MeterStyle=TitleStyle
Text=How Stephen Hawking Helped Redefine Humanity’s Existence #Separator#
LeftMouseUpAction=http://feedproxy.google.com/~r/time/topstories/~3/eXU-YCcCe4M/
[Title12]
Meter=String
MeterStyle=TitleStyle
Text=Russian spy: Theresa May visits Salisbury after 'brazen' attack #Separator#
LeftMouseUpAction=http://www.bbc.co.uk/news/uk-43414824
[Title13]
Meter=String
MeterStyle=TitleStyle
Text=Chemical Plant Explosion in Texas Leaves at Least 1 Critically Injured #Separator#
LeftMouseUpAction=http://feedproxy.google.com/~r/time/topstories/~3/YZYwqCa0zrQ/
[Title14]
Meter=String
MeterStyle=TitleStyle
Text=Russia spy: Allies condemn nerve agent attack #Separator#
LeftMouseUpAction=http://www.bbc.co.uk/news/world-europe-43415271
[Title15]
Meter=String
MeterStyle=TitleStyle
Text=Facebook launches Express Wi-Fi app for its local-operated hotspots #Separator#
LeftMouseUpAction=http://feedproxy.google.com/~r/Techcrunch/~3/R5JcfzyTl2E/
[Title16]
Meter=String
MeterStyle=TitleStyle
Text=Is YouTube Bad For Us #Separator#
LeftMouseUpAction=http://feedproxy.google.com/~r/time/topstories/~3/PPT3pzgeCFE/
[Title17]
Meter=String
MeterStyle=TitleStyle
Text=Ford is changing the way it builds vehicles #Separator#
LeftMouseUpAction=http://feedproxy.google.com/~r/Techcrunch/~3/GjAZyFxCZ4w/
[Title18]
Meter=String
MeterStyle=TitleStyle
Text=Ford says its electric SUV will be famous without having to shoot it into space #Separator#
LeftMouseUpAction=http://feedproxy.google.com/~r/Techcrunch/~3/Yo-QwcFX0Dc/
[Title19]
Meter=String
MeterStyle=TitleStyle
Text=The regulators of the Flint water crisis are embroiled in a new scandal #Separator#
LeftMouseUpAction=https://qz.com/1229634/the-michigan-agency-blamed-for-the-flint-disaster-is-embroiled-in-a-new-toxic-water-scandal/
[Title20]
Meter=String
MeterStyle=TitleStyle
Text=Ford takes aim at Toyota’s hybrid market lead with its new SUV lineup #Separator#
LeftMouseUpAction=http://feedproxy.google.com/~r/Techcrunch/~3/9kpX7BAd6HQ/
